-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 12:40:20 2024
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
DROP database if exists sakila;

CREATE SCHEMA IF NOT EXISTS `sakila` ;
USE `sakila` ;

-- -----------------------------------------------------
-- Table `sakila`.`Chamadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Chamadas` (
  `idChamadas` INT NOT NULL AUTO_INCREMENT,
  `Horarios` DATETIME NULL,
  `Quantidade_de_ligacoes` INT NULL,
  PRIMARY KEY (`idChamadas`)
) ENGINE=InnoDB;



-- -----------------------------------------------------
-- Table `sakila`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Pessoa` (
  `Nome` VARCHAR(45) NOT NULL,
  `Número` VARCHAR(45) NULL,
  `eMail` VARCHAR(45) NULL,
  `Chamadas_idChamadas` INT NOT NULL,
  PRIMARY KEY (`Nome`),
  INDEX `fk_Pessoa_Chamadas1_idx` (`Chamadas_idChamadas` ASC),
  CONSTRAINT `fk_Pessoa_Chamadas1`
    FOREIGN KEY (`Chamadas_idChamadas`)
    REFERENCES `sakila`.`Chamadas` (`idChamadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Música`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Música` (
  `Nome` VARCHAR(45) NOT NULL,
  `Artista` VARCHAR(45) NULL,
  `Tempo` DECIMAL(5,2) NULL,
  `Reprodução` INT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Historico` (
  `Site` VARCHAR(45) NOT NULL,
  `URL` VARCHAR(45) NULL,
  `Horario de acesso` DATETIME NULL,
  PRIMARY KEY (`Site`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Playlist` (
  `Titulo` VARCHAR(45) NOT NULL,
  `QuantMúsica` INT NULL,
  PRIMARY KEY (`Titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Música_has_Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Música_has_Playlist` (
  `Música_Nome` VARCHAR(45) NOT NULL,
  `Playlist_Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Música_Nome`, `Playlist_Titulo`),
  INDEX `fk_Música_has_Playlist_Playlist1_idx` (`Playlist_Titulo` ASC),
  INDEX `fk_Música_has_Playlist_Música1_idx` (`Música_Nome` ASC),
  CONSTRAINT `fk_Música_has_Playlist_Música1`
    FOREIGN KEY (`Música_Nome`)
    REFERENCES `sakila`.`Música` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Música_has_Playlist_Playlist1`
    FOREIGN KEY (`Playlist_Titulo`)
    REFERENCES `sakila`.`Playlist` (`Titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Pessoa_has_Chamadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Pessoa_has_Chamadas` (
  `Pessoa_Nome` VARCHAR(45) NOT NULL,
  `Chamadas_idChamadas` INT NOT NULL,
  PRIMARY KEY (`Pessoa_Nome`, `Chamadas_idChamadas`),
  INDEX `fk_Pessoa_has_Chamadas_Chamadas1_idx` (`Chamadas_idChamadas` ASC),
  INDEX `fk_Pessoa_has_Chamadas_Pessoa1_idx` (`Pessoa_Nome` ASC),
  CONSTRAINT `fk_Pessoa_has_Chamadas_Pessoa1`
    FOREIGN KEY (`Pessoa_Nome`)
    REFERENCES `sakila`.`Pessoa` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Chamadas_Chamadas1`
    FOREIGN KEY (`Chamadas_idChamadas`)
    REFERENCES `sakila`.`Chamadas` (`idChamadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Dragon City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`DragonCity` (
  `idDragonCity` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idDragonCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Ilhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Ilhas` (
  `idIlhas` INT NOT NULL,
  `Nome da ilha` VARCHAR(45) NULL,
  `DragonCity_idDragonCity` INT NOT NULL,
  PRIMARY KEY (`idIlhas`, `DragonCity_idDragonCity`),
  INDEX `fk_Ilhas_DragonCity1_idx` (`DragonCity_idDragonCity` ASC),
  CONSTRAINT `fk_Ilhas_DragonCity1`
    FOREIGN KEY (`DragonCity_idDragonCity`)
    REFERENCES `sakila`.`DragonCity` (`idDragonCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Tipo` (
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Habitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Habitat` (
  `idHabitat` INT NOT NULL,
  `QuantDragoes` INT NULL,
  `Ilhas_idIlhas` INT NOT NULL,
  `Tipo_Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabitat`, `Ilhas_idIlhas`, `Tipo_Tipo`),
  INDEX `fk_Habitat_Ilhas1_idx` (`Ilhas_idIlhas` ASC),
  INDEX `fk_Habitat_Tipo1_idx` (`Tipo_Tipo` ASC),
  CONSTRAINT `fk_Habitat_Ilhas1`
    FOREIGN KEY (`Ilhas_idIlhas`)
    REFERENCES `sakila`.`Ilhas` (`idIlhas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitat_Tipo1`
    FOREIGN KEY (`Tipo_Tipo`)
    REFERENCES `sakila`.`Tipo` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Dragões`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Dragões` (
  `idDragões` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Espécie` VARCHAR(45) NULL,
  `Nível` INT NULL,
  `Habitat_idHabitat` INT NOT NULL,
  PRIMARY KEY (`idDragões`, `Habitat_idHabitat`),
  INDEX `fk_Dragões_Habitat1_idx` (`Habitat_idHabitat` ASC),
  CONSTRAINT `fk_Dragões_Habitat1`
    FOREIGN KEY (`Habitat_idHabitat`)
    REFERENCES `sakila`.`Habitat` (`idHabitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Tipo_has_Dragões`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Tipo_has_Dragões` (
  `Dragões_nomeDragões` INT NOT NULL,
  `Tipo_Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dragões_idDragões`, `Tipo_Tipo`),
  INDEX `fk_Tipo_has_Dragões_Dragões1_idx` (`Dragões_idDragões` ASC),
  INDEX `fk_Tipo_has_Dragões_Tipo1_idx` (`Tipo_Tipo` ASC),
  CONSTRAINT `fk_Tipo_has_Dragões_Dragões1`
    FOREIGN KEY (`Dragões_idDragões`)
    REFERENCES `sakila`.`Dragões` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_has_Dragões_Tipo1`
    FOREIGN KEY (`Tipo_Tipo`)
    REFERENCES `sakila`.`Tipo` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
